#!/bin/bash

sshvm() {
  local vm_name=$1
  shift
  local vm_mac=$(virsh dumpxml $vm_name | grep -m 1 'mac address' | cut -d "'" -f 2)
  local vm_ip=$(arp -n | grep $vm_mac | cut -d ' ' -f 1)
  local tries=2
  while [ $tries -ge 0 ] ; do
    if [ -n "$vm_ip" ] ; then
      echo "SSHing to $vm_ip"
      ssh root@${vm_ip} -i ~/.ssh/id_rsa_vm -o StrictHostKeyChecking=no "$*"
      break
    else
      if [ $tries -eq 0 ] ; then
        echo "Could not reach VM."
      else
        echo "VM is not ready yet. Trying $tries more time(s) in 15 seconds."
        sleep 15
      fi
      vm_ip=$(arp -n | grep $vm_mac | cut -d ' ' -f 1)
      tries=$(echo "${tries}-1" | bc)
    fi
  done
}
